package com.cyvanta.affiliate_app.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

@Slf4j
@Service
public class SmsService {

    private final RestTemplate restTemplate = new RestTemplate();
    private final ObjectMapper objectMapper = new ObjectMapper();

    @Value("${sms.provider:}")
    private String provider;

    // --- Fast2SMS Config ---
    @Value("${sms.fast2sms.api-key:}")
    private String fast2smsApiKey;

    // --- Twilio Config (fallback) ---
    @Value("${sms.twilio.account-sid:}")
    private String twilioAccountSid;

    @Value("${sms.twilio.auth-token:}")
    private String twilioAuthToken;

    @Value("${sms.twilio.from-number:}")
    private String twilioFromNumber;

    @Value("${sms.twilio.service-id:}")
    private String twilioServiceId;

    /**
     * Send OTP via SMS using the configured provider.
     * Tries Fast2SMS first (Quick route, no DLT needed), then Twilio, then simulator fallback.
     */
    public boolean sendOtpSms(String phone, String otp) {
        log.info("[SMS] Attempting to send OTP to {} via provider={}", phone, provider);

        // --- Fast2SMS (Quick Route — no DLT needed) ---
        if (provider != null && provider.equalsIgnoreCase("fast2sms") && hasFast2SmsConfig()) {
            boolean sent = sendFast2SmsOtp(phone, otp);
            if (sent) return true;
            log.warn("[SMS] Fast2SMS failed, falling back to Twilio...");
        }

        // --- Twilio fallback ---
        if (hasTwilioConfig()) {
            if (twilioServiceId != null && !twilioServiceId.isBlank()) {
                boolean sent = sendTwilioVerify(phone);
                if (sent) return true;
                log.warn("[SMS] Twilio Verify API failed, falling back to Messages API");
            }
            boolean sent = sendTwilioSms(phone, otp);
            if (sent) return true;
            log.warn("[SMS] Twilio Messages API also failed for {}", phone);
        }

        // Simulator fallback — always log the OTP for dev/testing
        log.info("===========================================");
        log.info("[SMS SIMULATOR] OTP for {}: {}", phone, otp);
        log.info("===========================================");
        return false;
    }

    // ==================== Fast2SMS Quick Route ====================

    /**
     * Send OTP using Fast2SMS Quick SMS route (no DLT registration needed).
     * Uses international ILDO gateway — works with any Indian number.
     * OTP is generated by our app and sent as a message.
     * Verification is done locally in our DB (not via Fast2SMS API).
     */
    private boolean sendFast2SmsOtp(String phone, String otp) {
        // Extract 10-digit Indian mobile number (remove +91 or 91 prefix)
        String mobileNumber = extractIndianMobile(phone);
        if (mobileNumber == null) {
            log.error("[SMS] Cannot extract valid 10-digit Indian number from {}", phone);
            return false;
        }

        // Fast2SMS Quick SMS API (route=q means Quick/International — no DLT needed)
        String url = "https://www.fast2sms.com/dev/bulkV2"
            + "?authorization=" + fast2smsApiKey
            + "&route=q"
            + "&message=" + java.net.URLEncoder.encode(
                "Your Cyvanta Cashback verification code is " + otp + ". Valid for 10 minutes. Do not share.", 
                java.nio.charset.StandardCharsets.UTF_8)
            + "&numbers=" + mobileNumber;

        try {
            HttpHeaders headers = new HttpHeaders();
            headers.set("authorization", fast2smsApiKey);
            headers.set("cache-control", "no-cache");

            HttpEntity<String> request = new HttpEntity<>(null, headers);

            log.info("[SMS] Sending OTP via Fast2SMS Quick Route to {} (mobile={})", phone, mobileNumber);
            ResponseEntity<String> response = restTemplate.exchange(url, HttpMethod.GET, request, String.class);

            log.info("[SMS] Fast2SMS response: status={}, body={}", response.getStatusCode(), response.getBody());

            if (response.getStatusCode().is2xxSuccessful() && response.getBody() != null) {
                JsonNode json = objectMapper.readTree(response.getBody());
                boolean returnValue = json.has("return") && json.get("return").asBoolean();
                String message = json.has("message") ? json.get("message").asText() : "";

                if (returnValue) {
                    log.info("[SMS] Fast2SMS OTP sent successfully to {}", mobileNumber);
                    return true;
                }
                log.error("[SMS] Fast2SMS returned: return={}, message={}", returnValue, message);
            }
        } catch (Exception e) {
            log.error("[SMS] Fast2SMS sendOtp failed for {}: {}", phone, e.getMessage());
        }
        return false;
    }

    /**
     * Extract 10-digit Indian mobile number from various formats.
     * Handles: +919876543210, 919876543210, 9876543210, 09876543210
     */
    private String extractIndianMobile(String phone) {
        if (phone == null) return null;
        // Remove all non-digits
        String digits = phone.replaceAll("[^\\d]", "");

        if (digits.length() == 10) {
            return digits;
        } else if (digits.length() == 12 && digits.startsWith("91")) {
            return digits.substring(2);
        } else if (digits.length() == 11 && digits.startsWith("0")) {
            return digits.substring(1);
        }
        log.warn("[SMS] Could not extract 10-digit number from: {} (digits={})", phone, digits);
        return digits.length() >= 10 ? digits.substring(digits.length() - 10) : null;
    }

    /**
     * Check if Fast2SMS is the active provider.
     * Fast2SMS OTP verification is done locally via our DB — no external verify API needed.
     */
    public boolean isFast2SmsActive() {
        return provider != null && provider.equalsIgnoreCase("fast2sms") && hasFast2SmsConfig();
    }

    private boolean hasFast2SmsConfig() {
        boolean configured = fast2smsApiKey != null && !fast2smsApiKey.isBlank();
        if (!configured) {
            log.warn("[SMS] Fast2SMS config check failed — apiKey={}",
                fast2smsApiKey != null ? "SET" : "MISSING");
        }
        return configured;
    }

    // ==================== Twilio Methods (Fallback) ====================

    /**
     * Verify an OTP code that was sent via Twilio Verify API.
     * Call this from the controller when verifying a phone-based OTP.
     * Returns true if Twilio confirms the code is correct.
     */
    public boolean verifyTwilioCode(String phone, String code) {
        if (twilioServiceId == null || twilioServiceId.isBlank() || !hasTwilioConfig()) {
            return false;
        }

        String url = String.format(
            "https://verify.twilio.com/v2/Services/%s/VerificationCheck",
            twilioServiceId
        );

        HttpHeaders headers = new HttpHeaders();
        headers.setBasicAuth(twilioAccountSid, twilioAuthToken);
        headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);

        MultiValueMap<String, String> body = new LinkedMultiValueMap<>();
        body.add("To", phone);
        body.add("Code", code);

        try {
            HttpEntity<MultiValueMap<String, String>> request = new HttpEntity<>(body, headers);
            ResponseEntity<String> response = restTemplate.postForEntity(url, request, String.class);

            if (response.getStatusCode().is2xxSuccessful() && response.getBody() != null) {
                JsonNode json = objectMapper.readTree(response.getBody());
                String status = json.has("status") ? json.get("status").asText() : "";
                if ("approved".equals(status)) {
                    log.info("[SMS] Twilio Verify confirmed OTP for {}", phone);
                    return true;
                }
                log.warn("[SMS] Twilio Verify check returned status={} for {}", status, phone);
            }
        } catch (Exception e) {
            log.error("[SMS] Twilio Verify check failed for {}: {}", phone, e.getMessage());
        }
        return false;
    }

    private boolean hasTwilioConfig() {
        boolean configured = twilioAccountSid != null && !twilioAccountSid.isBlank()
            && twilioAuthToken != null && !twilioAuthToken.isBlank();
        if (!configured) {
            log.warn("[SMS] Twilio config check failed — accountSid={}, authToken={}",
                twilioAccountSid != null ? "SET" : "MISSING",
                twilioAuthToken != null ? "SET" : "MISSING");
        }
        return configured;
    }

    /**
     * Use Twilio Verify API to send a verification code.
     */
    private boolean sendTwilioVerify(String phone) {
        String url = String.format(
            "https://verify.twilio.com/v2/Services/%s/Verifications",
            twilioServiceId
        );

        HttpHeaders headers = new HttpHeaders();
        headers.setBasicAuth(twilioAccountSid, twilioAuthToken);
        headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);

        MultiValueMap<String, String> body = new LinkedMultiValueMap<>();
        body.add("To", phone);
        body.add("Channel", "sms");

        try {
            HttpEntity<MultiValueMap<String, String>> request = new HttpEntity<>(body, headers);
            ResponseEntity<String> response = restTemplate.postForEntity(url, request, String.class);

            if (response.getStatusCode().is2xxSuccessful()) {
                log.info("[SMS] OTP sent via Twilio Verify API to {}", phone);
                return true;
            }

            log.error("[SMS] Twilio Verify API responded with status {} for {}. Response: {}",
                response.getStatusCode(), phone, response.getBody());
        } catch (Exception e) {
            log.error("[SMS] Twilio Verify API failed for {}: {}", phone, e.getMessage());
            if (e.getMessage() != null && e.getMessage().contains("60200")) {
                log.error("[SMS] Twilio Error 60200: The phone number {} is not verified. " +
                    "On Twilio trial accounts, you can only send to verified numbers. " +
                    "Go to https://console.twilio.com/us1/develop/phone-numbers/manage/verified " +
                    "to add verified numbers, or upgrade your Twilio account.", phone);
            }
        }
        return false;
    }

    /**
     * Fallback: use raw Twilio Messages API to send a custom OTP message.
     */
    private boolean sendTwilioSms(String to, String otp) {
        String url = String.format("https://api.twilio.com/2010-04-01/Accounts/%s/Messages.json", twilioAccountSid);
        HttpHeaders headers = new HttpHeaders();
        headers.setBasicAuth(twilioAccountSid, twilioAuthToken);
        headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);

        MultiValueMap<String, String> body = new LinkedMultiValueMap<>();
        body.add("From", twilioFromNumber);
        body.add("To", to);
        body.add("Body", "Your Cyvanta Cashback OTP is " + otp + ". It expires in 10 minutes.");

        try {
            HttpEntity<MultiValueMap<String, String>> request = new HttpEntity<>(body, headers);
            ResponseEntity<String> response = restTemplate.postForEntity(url, request, String.class);
            if (response.getStatusCode().is2xxSuccessful()) {
                log.info("[SMS] OTP sent via Twilio Messages API to {}", to);
                return true;
            }
            log.error("[SMS] Twilio Messages API responded with status {} for {}. Response: {}",
                response.getStatusCode(), to, response.getBody());
        } catch (Exception e) {
            log.error("[SMS] Twilio Messages API failed for {}: {}", to, e.getMessage());
            if (e.getMessage() != null && e.getMessage().contains("21608")) {
                log.error("[SMS] Twilio Error 21608: The 'To' number {} is unverified. " +
                    "Trial accounts can only send to verified caller IDs. " +
                    "Verify the number at https://console.twilio.com or upgrade your account.", to);
            }
        }
        return false;
    }
}
